#define dv_videosegment_t_i                      0
#define dv_videosegment_t_k                      4
#define dv_videosegment_t_bs                     8
#define dv_videosegment_t_mb                     16
#define dv_videosegment_t_isPAL                  5256
#define dv_macroblock_t_size                     1048
#define dv_macroblock_t_b                        24
#define dv_macroblock_t_eob_count                1044
#define dv_macroblock_t_vlc_error                1040
#define dv_macroblock_t_qno                      1032
#define dv_macroblock_t_sta                      1036
#define dv_macroblock_t_i                        0
#define dv_macroblock_t_j                        4
#define dv_macroblock_t_k                        8
#define dv_block_t_size                          168
#define dv_block_t_coeffs                        0
#define dv_block_t_dct_mode                      128
#define dv_block_t_class_no                      132
#define dv_block_t_reorder                       136
#define dv_block_t_reorder_sentinel              144
#define dv_block_t_offset                        152
#define dv_block_t_end                           156
#define dv_block_t_eob                           160
#define dv_block_t_mark                          164
#define bitstream_t_buf                          16
#define DV_QUALITY_BEST                          5
#define DV_QUALITY_FASTEST                       0
#define DV_QUALITY_COLOR                         1
#define DV_QUALITY_AC_MASK                       6
#define DV_QUALITY_DC                            0
#define DV_QUALITY_AC_1                          2
#define DV_QUALITY_AC_2                          4
#define DV_WEIGHT_BIAS                           6
