# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# ZLIB_WINAPI_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set ZLIB_WINAPI_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The ZLIB_WINAPI_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/x86_64/libarchive/CMakeFiles/CMakeTmp/src.c
# Executable    : /mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/x86_64/libarchive/CMakeFiles/cmTC_64aa9-ZLIB_WINAPI_EXITCODE.exe
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.5/Modules/CheckCSourceRuns.cmake
#                 [2]	/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/x86_64/libarchive/CMakeLists.txt
#                 [1]	/mnt/e/Users/john/Documents/MultimediaTools-mingw-w64/sandbox/x86_64/libarchive/CMakeLists.txt

set( ZLIB_WINAPI_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

